
name: Ubuntu SSH Virtual Machine (Tailscale)
on: 
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Preparing Linux Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y curl

    - name: Installing Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh

    - name: Connecting to Tailscale Mesh
      run: |
        sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}

    - name: Setting Up the Ubuntu Environment
      run: bash linux-ssh.sh
      env:
        LINUX_USERNAME: ${{ secrets.LINUX_USERNAME }}
        LINUX_USER_PASSWORD: ${{ secrets.LINUX_USER_PASSWORD }}
        LINUX_MACHINE_NAME: ${{ secrets.LINUX_MACHINE_NAME }}

    - name: Keep Running Ubuntu System and keepAlive
      run: sleep 6h